### ISSUE TITLE
Number of deleted entries on del()

### ISSUE THREAD

**Issue by guyellis** [tcs-de/nodecache#24]
In the documentation for del() it says "...Returns the number of deleted entries..."

Will this always be 0 or 1?

**Comment by matthieusieben** [comment]
If the key argument is a string, yes.
If it is an array of string keys, then it will return the number of matching elements that were removed.

**Comment by mpneuried** [comment]
That's right. You'll get the count of deleted elements.
see: https://github.com/tcs-de/nodecache#delete-multiple-keys-mdel
