### ISSUE TITLE
Returns reference not copy

### ISSUE THREAD

**Issue by cheshirecatalyst** [tcs-de/nodecache#27]
For instance fetching some seldom changing data from the db caching it, then applying i18n to the result, pollutes subsequent cache fetches for the plain english result to be translated into another language.

**Comment by mpneuried** [comment]
See [version 2.2.0 ](https://github.com/tcs-de/nodecache/releases/tag/2.2.0) for the solution

**Comment by mpneuried** [comment]
After the issue #30 i revoked the version 2.2.0 due to the breaking change and made a major release `3.0.0` that will do the clone by default, but with an option to disable it.

**Comment by cheshirecatalyst** [comment]
Thanks ^_^
