### ISSUE TITLE
Optional prefetching?

### ISSUE THREAD

**Issue by cheshirecatalyst** [tcs-de/nodecache#31]
Pull request momentarily.

**Comment by tcs-de** [comment]
i won't add a prefetch feature into this module.
It should stay as simple as possible and do only one thing.

I found a module witch sounds similar to your needs ... 
https://www.npmjs.com/package/pear

But you can create your own simple module that uses node-cache as engine under the hood and do the prefetching.
Or you can just require node-cache and overwrite the methods to change it's behaviour.
