### ISSUE TITLE
Aborts on cache HTTPS requests

### ISSUE THREAD

**Issue by szeist** [tcs-de/nodecache#42]
Caching request objects not working from version 3.0.0.

I've created a gist to reproduce the issue: https://gist.github.com/szeist/777d67619579d4218144

**Comment by mpneuried** [comment]
Hi, 
as described [here as Breaking change](https://github.com/tcs-de/nodecache#version-3x) it is possible to deactivate the cloning be setting the option "useClones".

This code should fix your problem ;-)

```js
// ...
beforeEach(() => cache = new nodeCache({useClones: false}));
// ...
```
