### ISSUE TITLE
Releasing objects manually vs waiting for automatic cleanup

### ISSUE THREAD

**Issue by rdbell** [tcs-de/nodecache#43]
I've set up a cache of objects using nodecache. These objects get "processed" roughly 10s after being inserted into the cache. After they're processed I don't need to reference them and they can be destroyed.

Is it more resource efficient to .del() them after processing them manually, or to let them automatically expire after ~15 seconds?

**Comment by mpneuried** [comment]
Hi,
technically the expire is done by internal a timestamp stored in the object metadata.
With a interval defined in `checkperiod` node-cache searches for every object with `obj.timestamp != 0 && obj.timestamp <= Date.now()` and deletes them. So every expired object will destroyed.

The most efficient way for you case would be so set `checkperiod = 0` and delete manually without using the expire feature.
In this case node-cache can save the memory for the expire timespace and will not start the internal interval to clean up the cache every x seconds.

Hope this information helps.

**Comment by rdbell** [comment]
Thanks for the explanation!
