### ISSUE TITLE
#<Promise> is not a promise

### ISSUE THREAD

**Issue by echo66** [tcs-de/nodecache#47]
Greetings! I'm using node-cache module and I'm trying to store promises in the cache. Take a look at the following code snippet:

```javascript
router.get('/test', (req, res) => {
    myCache.get('example', ( err, value ) => {
      if (!err) {
        if (value == undefined) {
          value = new Promise((resolve,reject) => {
            resolve("hey");
          });
          myCache.set('example', value);
        } 
        console.log(value instanceof Promise);
        value.then((str) => console.log(str));
        res.status(200);
        res.send();
      } else {
        logger.error(err);
        res.status(500);
        res.send();
      }
    });
  });
```

The first request to that endpoint produces the following console output:
true
hey

The second request produces this:
true
TypeError: #<Promise> is not a promise

So....a promise "is not" a promise? wat

**Comment by mpneuried** [comment]
Do you use the option `useClones = false` as described in the [options](https://github.com/tcs-de/nodecache#options)? 

>**Note:** `true` is recommended, because it'll behave like a server-based caching. You should set `false` if you want to save complex variable types like functions, promises, regexp, ...

**Comment by echo66** [comment]
@mpneuried , thanks for the quick answer! :D

And thanks for not saying (although I deserve it) to RTFM.

**Comment by mpneuried** [comment]
No problem.
I guess you where so thrilled to use the module instead of reading the boring manuals ...  :speak_no_evil:

**Comment by echo66** [comment]
Well, to be honest... yes :P
