### ISSUE TITLE
How to obtain TTL of the rest of the time

### ISSUE THREAD

**Issue by tangtang520** [tcs-de/nodecache#49]
How to obtain TTL of the rest of the time

**Comment by mpneuried** [comment]
There is currently no option to retrieve the ttl of a key.

**Comment by mpneuried** [comment]
I added a method `myCache.getTtl( key, [callback] )` to handle your need.
https://github.com/tcs-de/nodecache#get-ttl-getttl

**Comment by filly82** [comment]
when i try to get the TTL of an existing key my app just crash without any error. sync and async version.
when i try to get the TTL of an unknown key then i get an undefined like the doc says. what am i doing wrong?

**Comment by mpneuried** [comment]
can you provide me an example?
i tested it here: https://tonicdev.com/mpneuried/5718b7f13ffa30120097000f

**Comment by filly82** [comment]
of course i cannot reproduce it :(
this is basically what i am doing, but it works on that platform: https://tonicdev.com/5718bce2fab6891400f3d34c/5718c1e4a1e962110076c58e
