### ISSUE TITLE
Get method value is wrong, when the value type is Map

### ISSUE THREAD

**Issue by luozhanhong** [tcs-de/nodecache#64]
```javascript
var NodeCache = require("node-cache");
var myCache = new NodeCache();

var map = new Map();
map.set(1, 1);
console.log(map);
// Map { 1 => 1 }

myCache.set("myKey", map, function (err, success) {
	if (!err && success) {
		console.log(success);
		// true
	}
});

myCache.get("myKey", function (err, value) {
	if (!err) {
		if (value == undefined) {
			console.log("undefined");
		} else {
			console.log(value);
			// Map {}
		}
	}
});
```

**Comment by mpneuried** [comment]
```
var myCache( { useClones: false } );
```

See [options](https://github.com/tcs-de/nodecache#options).
>- `useClones`: *(default: `true`)* en/disable cloning of variables. If `true` you'll get a copy of the cached variable. If `false` you'll save and get just the reference.  
**Note:** `true` is recommended, because it'll behave like a server-based caching. You should set `false` if you want to save complex variable types like functions, promises, regexp, ...

**Comment by luozhanhong** [comment]
Thank you.
