### ISSUE TITLE
delete first 10 or 15 records

### ISSUE THREAD

**Issue by hcoderonly** [tcs-de/nodecache#65]
I was just wondering if there is a functionality in node cache for deleting the first 10(can be configurable?) records from the dictionary to avoid oversizing the node cache?
or is there any max limit into the node cache library that I should know?
Please let me know Thanks

**Comment by mpneuried** [comment]
Hi, there is no max limit.
Currently the only way to automatic clear teh cache is by define a `ttl`.

ut there is already a existing Issues/TODO #63 to add a function like you described.
