### ISSUE TITLE
Clarify expiration functionality documentation

### ISSUE THREAD

**Issue by kibertoad** [tcs-de/nodecache#68]
Currently it is not clear whether expired entry are automatically purged from memory or only removed when you try to get them (so that your memory usage can potentially grow uncontrollably and explicit housekeeping for expired entries should be implemented).
Documentation mentions "Keys can have a timeout after which they expire and are cleaned from the cache", but it is not clear, whether values themselves are deleted as well.

**Comment by mpneuried** [comment]
During the internal check the method `.del( key )` is used to remove expired keys.

So the expired keys will be **deleted** with [`delete @data[ key ]`](https://github.com/tcs-de/nodecache/blob/master/_src/lib/node_cache.coffee#L218)

Does this clear your question?

**Comment by mpneuried** [comment]
And i think "cleaned from the cache" should be enough and a `ttl` of a key will not interpreted as *there will be garbage left in the cache*.

**Comment by kibertoad** [comment]
Documentation is ambiguous :(.

Currently it says "**Keys** can have a timeout after which they expire and are cleaned from the cache." - nowhere it says that "expired keys will be deleted with delete @data[ key ]" (because that operation actually does not only delete the key but also a value for that key). Could you please add the 

"So the expired keys will be deleted with delete @data[ key ]"

somewhere in the documentation?
